---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: iotite

description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 43 

modules:

  - type: akmods
    install: []
    nvidia-driver: nvidia

  - type: dnf
    install:
      packages:
        - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm
        - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm
    
  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        # - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm
        # - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm
      copr: 
        - shdwchn10/AllTheTools
    install:
      packages:
        - zstd
        - sbsign
        # - ffmpeg
        - fzf
        - libheif
        - libva-utils
        - lshw
        - net-tools
        - nvme-cli
        - nvtop
        - openssl
        - powerstat
        - symlinks
        - tcpdump
        - tmux
        - traceroute
        - wireguard-tools
        - intel-gmmlib
        - intel-media-driver
        - samba
        - cockpit
        - cockpit-podman
        - intel-undervolt
        - msr-tools
        - tailscale
        - policycoreutils-python-utils
        - nnn
        - dmtcp
        - libinput-utils
        - openssl-devel
        - hashcat
        - stress
        - cargo
        - fd-find
        - cmake
        - meson
        - gcc-c++
        - gcc
        - igt-gpu-tools
        - lm_sensors
        - uv
        - kernel-tools
        - tailscale
        - zoxide
        - bat
        - eza
        - zsh
        - topgrade
        - powertop
    replace:
      - from-repo: rpmfusion-free
        install-weak-deps: false
        packages:
          - new: ffmpeg
            old: ffmpeg-free


  - type: signing 
