---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: iotite

description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 42 # latest is also supported if you want new updates ASAP

modules:

  - type: akmods
    install: []
    nvidia-driver: nvidia
    
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr: 
        - shdwchn10/AllTheTools
    install:
      - policycoreutils-python-utils
      - nnn
      - dmtcp
      - libinput-utils
      - openssl-devel
      - lm_sensors
      - hashcat
      - stress
      - cargo
      - fd-find
      - cmake
      - meson
      - gcc-c++
      - gcc
      - igt-gpu-tools
      - uv
      - zoxide
      - kernel-tools
      - tailscale
      - bat
      - eza
      - zsh
      - msr-tools
      - topgrade
      - powertop

    remove:
      packages: []
      
  - from-file: wunker.yml
  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
