---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: iotite

description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 42 # latest is also supported if you want new updates ASAP

modules:

  - type: akmods
    install: []
    nvidia-driver: nvidia
    
  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr: 
        - shdwchn10/AllTheTools
    install:
      packages:
        - samba
        - cockpit
        - cockpit-podman
        - intel-undervolt
        - msr-tools
        - tailscale
        - policycoreutils-python-utils
        - nnn
        - dmtcp
        - libinput-utils
        - openssl-devel
        - hashcat
        - stress
        - cargo
        - fd-find
        - cmake
        - meson
        - gcc-c++
        - gcc
        - igt-gpu-tools
        - lm_sensors
        - uv
        - kernel-tools
        - tailscale
        - zoxide
        - bat
        - eza
        - zsh

        - topgrade
        - powertop
  - from-file: wunker.yml
  - type: signing 
