---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: iotite

description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 43 

modules:

  - type: akmods
    install: []
    nvidia-driver: nvidia

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr: 
        - shdwchn10/AllTheTools
      nonfree: rpmfusion
    install:
      packages:
        - nvtop
        - zstd
        - sbsign
        - fzf
        - lshw
        - net-tools
        - nvme-cli
        - nvtop
        - openssl
        - powerstat
        - symlinks
        - tcpdump
        - tmux
        - traceroute
        - wireguard-tools
        - samba
        - cockpit
        - cockpit-podman
        - intel-undervolt
        - msr-tools
        - tailscale
        - policycoreutils-python-utils
        - nnn
        - dmtcp
        - libinput-utils
        - openssl-devel
        - hashcat
        - stress
        - cargo
        - fd-find
        - cmake
        - meson
        - gcc-c++
        - gcc
        - igt-gpu-tools
        - lm_sensors
        - uv
        - kernel-tools
        - tailscale
        - zoxide
        - bat
        - eza
        - zsh
        - topgrade
        - powertop

  - type: dnf
    repos:
      nonfree: rpmfusion
    install:
      allow-erasing: true
      packages:
        - ffmpeg-libs
        - ffmpeg
        - libheif
        - libva-utils
        - intel-gmmlib
        - intel-media-driver
        - libva-nvidia-driver
    group-install:
      packages:
        - multimedia
  - type: signing 
