---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: iotite

description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 43 

modules:

  - type: akmods
    install: []
    nvidia-driver: nvidia
    
  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr: 
        - shdwchn10/AllTheTools
    install:
      packages:
        - zstd
        - sbsign
        - ffmpeg
        - fzf
        - libheif
        - libva-utils
        - lshw
        - net-tools
        - nvme-cli
        - nvtop
        - openssl
        - powerstat
        - symlinks
        - tcpdump
        - tmux
        - traceroute
        - wireguard-tools
        - intel-gmmlib
        - libva-intel-media-driver
        - samba
        - cockpit
        - cockpit-podman
        - intel-undervolt
        - msr-tools
        - tailscale
        - policycoreutils-python-utils
        - nnn
        - dmtcp
        - libinput-utils
        - openssl-devel
        - hashcat
        - stress
        - cargo
        - fd-find
        - cmake
        - meson
        - gcc-c++
        - gcc
        - igt-gpu-tools
        - lm_sensors
        - uv
        - kernel-tools
        - tailscale
        - zoxide
        - bat
        - eza
        - zsh
        - topgrade
        - powertop
    replace:
      # mitigate upstream packaging bug: https://bugzilla.redhat.com/show_bug.cgi?id=2332429
      # swap the incorrectly installed OpenCL-ICD-Loader for ocl-icd, the expected package
      - from-repo: fedora
        install-weak-deps: false
        packages:
          - new: ocl-icd
            old: OpenCL-ICD-Loader
    
      # use override to replace mesa and others with less crippled versions
      - from-repo: fedora-multimedia
        install-weak-deps: false
        packages:
          - libva
          - intel-vpl-gpu-rt
          - intel-mediasdk
          - mesa-dri-drivers
          - mesa-filesystem
          - mesa-libEGL
          - mesa-libGL
          - mesa-libgbm
          - mesa-va-drivers
          - mesa-vulkan-drivers


  - type: signing 
